import Head from 'next/head';

interface IHeadTitle {
  title: string;
}

const AppHead: React.FC<IHeadTitle> = ({ title }): JSX.Element => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default AppHead;
