import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import { Products } from '@/components/products';
import { BaseLayout } from '@/layout/base-layout';
import { IProducts } from '@/interfaces/products';

const Home: NextPage<IProducts> = ({ products }): JSX.Element => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BaseLayout>
        <main>
          <Products products={products} />
        </main>
      </BaseLayout>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (): Promise<{
  props: IProducts;
}> => {
  const response = await fetch(`${process.env.API_URL}/products?offset=0&limit=20&sortBy=latest`);
  const products = await response.json();
  return {
    props: { products },
  };
};
