import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { BaseLayout } from '../layout/base-layout';

const Home: NextPage = () => {
  useEffect(() => {
    (async () => {
      try {
        const response = await fetch(
          'http://localhost:5000/api/products?offset=0&limit=20&sortBy=latest'
        );
        const data = await response.json();
        console.log('data', data); //FIXME:
      } catch (error) {
        console.log('error', error); //FIXME:
      }
    })();
  }, []);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BaseLayout>
        <main>main</main>
      </BaseLayout>
    </>
  );
};

export default Home;
